- README.md
Signed-off-by: Daniel Krook <krook@us.ibm.com>
> Add contribution guidance.

- index.h
Signed-off-by: felmue <reg2000@gmx.net>
> Open number keypad for number fields

- .gitmodules
Two submodules are currently missing to build the example MQ7 and dust sensor
> add missing submodules for MQ7 and dust sensor examples

- README.md
- contributing/PULL-REQUESTS.md
- doc/howToBuildADuck.md
- Standardize capitalization of "PlatformIO"
- Fix link to Slack
- Add Git LFS prerequisite
- Remove redundant "force" wording in the Captive Portal section
> Minor documentation updates.

- doc/howToBuildADuck.md
re-added the empty lines to make the md-to-pdf renderer happy.
some trivial spelling and capitalization fixes while i was at it.
> some trivial format and spelling changes

- ClusterDuck.cpp
- ClusterDuck.h
- examples/PapaDuckExample/PapaDuckExample.ino
this are tested fixes for 
* the decoder memleak (which doesnt have an issue#) and 
* the ghost packets #50
> fix memleak and ghost packets

- .gitignore
- ClusterDuck.cpp
- ClusterDuck.h
- doc/howToBuildADuck.md
- examples/BMP180Example/platformio.ini
- examples/BMP280Example/platformio.ini
- examples/DHT11Example/platformio.ini
- examples/DuckLinkExample/platformio.ini
- examples/DustSensorExample/platformio.ini
- examples/MQ7Example/platformio.ini
- examples/MamaDuckExample/platformio.ini
As discussed with @TimoWielink
> OTA via Captive Portal

- ClusterDuck.cpp
I added a simple stop for Lora when the OTA starts. and a safe reboot when the .bin file is successfully uploaded
> add safe reboot and disable lora when OTA starts

- ClusterDuck.cpp
- cdpcfg.h
silenced some compiler warnings.
added another ttgo board type.
build tested on all three types.
> minor cleanup and a third board type

- ClusterDuck.cpp
- ClusterDuck.h
- cdpcfg.h
- examples/PapaDuckExample/PapaDuckExample.ino
- examples/TTGOGPSExample/TTGOGPSExample.ino
> 88 Datatypes WIP

- ClusterDuck.cpp
- ClusterDuck.h
> 88 datatypes

- ClusterDuck.cpp
- ClusterDuck.h
- cdpcfg.h
- index.h
collected commits over the last days.
* a bit of infrastructure for more flexible board defs: c029be1 and c8ab18c and dd533a3 
* four more boards: df55b16 and fcfbb09
* fix "default to heltec v2 board": cdc6342 
* fix "timer kills ota update": de9a2ba 
* minor whitespace cleanup: 471e7ec 
testbuild "all boards" still running, but more than one env completed already, so syntax ok.
> Kw26 collection PR

- ClusterDuck.cpp
- ClusterDuck.h
- examples/DuckLinkExample/.gitignore
- examples/PAPA_IRIDIUM/DishDuck_Hybrid/DishDuck_Hybrid.ino
- examples/PAPA_IRIDIUM/DishDuck_Hybrid/README.md
- examples/PAPA_IRIDIUM/DishDuck_Sat/DishDuck_Sat.ino
- examples/PAPA_IRIDIUM/DishDuck_Sat/README.md
- examples/PAPA_IRIDIUM/PAPA_IRIDIUM.ino
- examples/TTGOGPSExample/TTGOGPSExample.ino
DishDuck V.1 was cleaned up and added some formatting for easy readability. DishDuck Hybrid (a.k.a V.2) is out, In Dishduck V.2 the modified PAPA can switch between using WiFi and Iridium. This is a change from V.1 in which you could only send data over Iridium.  V.2 Will use WiFi when it is available and if any reason it disconnects or goes down the PAPA Duck will switch over to sending data via Iridium RockBlock. 
This code has been tested multiple times and works. There will be few tweaks here and there later on down the road but functions for now.
> 90 dishduck v2

- ClusterDuck.cpp
- ClusterDuck.h
- cdp-bloom.cpp
- cdp-bloom.h
- cdpcfg.h
- index.h
working WIP bloomfilter for MESH dedup
* "working"
* runs "PATH" and "BLOOM" in parallel, and compares their relay decision (and complains if they disagree)
* it currently only is applied to _incoming_ packets (so self-generated packets would be relayed (once))
* adding self-generated pkts to BF would be a lot easier if we were consistenly passing around Packet structures
(and this adds the pile of kw26a commits from the separate PR too)
> Wip bloomfilter

- ClusterDuck.cpp
- examples/PapaDuckExample/PapaDuckExample.ino
Fix internet connection when no ssid specified
> Hotfix PapaDuck

- ClusterDuck.cpp
#114 As for right now I just commented out this section. Did not know if wanted to permanently erase that for now. Also I tried just the (false) argument that did not work the AP still showed up until I just commented everything out. I tested it and the ping and pong work and I am getting my RSSI values.
> fix detector duck

- .gitmodules
- examples/TTGO-TBeam/TBeam_Power_Example/TBeam_Power_Example.ino
Its still a WIP since, it wont publish the full string but only small parts.
In the example file starting from line 68 you can see the other information commented out. It is only able to publish it up to IoT when its a small string.
Does this go wrong when making into JSOn?
> 102 Add Example for interacting with T-Beam APX20 power chip

- .gitmodules
- examples/TTGO-TBeam/TBEAM_LED_Example/TBEAM_LED_Example.ino
> Add Support for ws2812 LED 

- README.md
* Added button for the wiki, like there is for Slack and license.
* Changed case of "Wiki"
> Add button for wiki.

- README.md
* Fixed wiki link.
* Slack inviter still expired though
> Fix button for wiki.

- index.h
> Add character counter into Captive Portal 

- src/DuckNet.cpp
- src/include/DuckNet.h
- src/include/wifiCredentials.h
I have updated the UI for the WiFi setup portal `192.168.1.1/wifi`
> Update Wifi Setup Portal

- src/DuckLora.cpp
- src/DuckNet.cpp
Make sure the instance is actually stored when created otherwise it's not a singleton.
> Fixes singleton implementation

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
A starting point to implement the template described in the [CDP Release Versions ](https://docs.google.com/document/d/13wU1D2KZD0Tuw_Xe0coD3LnD5xTalToQ_F5NZ0sCzYA/edit#)doc.
> Add a pull request template.

- README.md
- examples/2.Custom-Mama-Example/Custom-Mama-Example.ino
- library.json
- library.properties
- src/DuckDisplay.cpp
- src/DuckDisplay.h
- src/DuckRadio.cpp
**Update Submodules and Display component**
---
Updates Submodules and changed display component to accept `std::vector<byte>` instead of `String`
Patch
#164 
Updated version number to reflect changes 
**Features changed**
Update RadioLib
Update Arduino-Timer
Update ESPAsyncWebserver
Rebuild Display Components to accept new DUID
> Update Submodules and Display component

- README.md
- examples/1.Ducks/PapaDuck/PapaDuck.ino
- examples/2.Custom-Mama-Example/Custom-Mama-Example/Custom-Mama-Example.ino
- library.json
- library.properties
- src/DuckDisplay.cpp
- src/DuckDisplay.h
Added a `sendBuffer(); `method to papa display sections
_**Patch**_
closes #163 
All tested
**Version 2.0.3**
> Update Custom Mama and display Papa

- README.md
- examples/2.Custom-Mama-Example/Custom-Mama-Example/Custom-Mama-Example.ino
- examples/4.Ble-Duck-App/Ble-Duck-App/Ble-Duck-App.ino
- library.properties
Patch v2.0.4
Fixed BLE Duck Sender ID not populating
> Patch Fix BLE Duck

- .travis.yml
- README.md
- examples/8.Encryption/DecryptionPapaDuck/DecryptionPapaDuck.ino
- library.properties
Add Encryption and Decryption for AES 256 CTR
Add Decryption PapaDuck example
Update version to v2.1.5
> add decryption example

- .github/ISSUE_TEMPLATE/feature_request.md
Describe at a high level the solution you're providing
A fix to this very template
Is this a patch, a minor version change, or a major version change
Definitely minor
Is this related to an open issue?
It was, #183
Additional context
Please merge me
> Simplify the pull request template.

- examples/7.TTGO-TBeam-Examples/TTGOGPSExample/TTGOGPSExample.ino
---
name: Fix TTGOGPS-Example
about: Fix GPS sending
title: 'Fix TTGOGPS-Example'
labels: 'Bug'
assignees: 'Nick Feuer'
---
GPS example was only sending GPS data once and not on the timer. Was in a limbo state
Patch
> Fix TTGOGPS-Example

- examples/1.Ducks/PapaDuck/PapaDuck.ino
---
name: PapaDuck Queue
about: Adding a queue for received messages
title: 'PapaDuck Queue'
labels: 'Feature'
assignees: 'Nick Feuer'
---
Added a queue to the PapaDuck for messages that failed to publish
Minor
#189, #85 
Will publish after connecting to cloud
> PapaDuck Queue

- .github/pull_request_template.md
I fixed this template. For real this time.
Patch.
No.
> Fix the pull request template. It had extraneous info on top.

- README.md
- library.json
- src/DuckRadio.cpp
- src/DuckUtils.cpp
We were using the default value for LoRa frequency even when specified outside of the `cdpcfg.h`.
Patch
> Fix setting custom frequencies

- .travis.yml
- src/CdpPacket.h
Fixes: https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/13
Added basic cppcheck on src/
Patch
#13 
This will introduce an error to the build, which I'm going to fix in the next commit.
I haven't looked at all of the cppcheck flags yet, but this seems like a reasonable place to start.
This doesn't lint any example code, but I can certainly add that.
> add cppcheck to .travis.yml

- src/include/DuckNet.h
- src/include/DuckUtils.h
Fix compilation errors for Arduino Zero board and DuckLink example,
Patch
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/203
> Fix compilation errors for Arduino Zero

- README.md
- library.json
- src/CdpPacket.h
- src/DuckUtils.cpp
Hotfix to compile error for not being able to convert a `const byte *` to `byte *`
Patch
> Fix for conversion error

- contributing/PULL-REQUESTS.md
No version change
Followup from #201
> add static code analysis to documentation.

- CONTRIBUTING.md
- README.md
Signed-off-by: Daniel Krook <krook@us.ibm.com>
Added link to the weekly townhalls
Minor, no code.
> Add link to town hall

- src/DuckNet.cpp
Mostly minor indentation fixes.
No functional changes.
> fix indentation

- README.md
- examples/3.Sensor-Examples/WS2812Example/WS2812Example.ino
- library.json
- library.properties
- src/DuckUtils.cpp
WS2812 Setup method was not calles
Patch
> Ws2812 Led missing setup statement

- README.md
- library.json
- library.properties
- src/Ducks/Duck.cpp
Prevent calling serial print CDP version before initializing serial.
Hotfix
> hotfix serial version

- CONTRIBUTING.md
- docs/html/cdpcfg_8h_source.html
- examples/2.Custom-Mama-Example/Custom-Mama-Example/Custom-Mama-Example.ino
- examples/6.PaPi-DMS-Lite-Examples/PapiDuckExample-wifi/PapiDuckExample-wifi.ino
- src/ClusterDuck.cpp
- src/include/cdpcfg.h
Encountered some typos
Patch
No
...
> various typos

- README.md
- library.json
- library.properties
- src/DuckUtils.cpp
- src/include/cdpcfg.h
SCL adn SDA pins were wrong on CdpCfg.h
patch
> T-beam oled pins defined wrong

- README.md
- examples/1.Ducks/DetectorDuck/.gitignore
- examples/1.Ducks/DetectorDuck/platformio.ini
- examples/1.Ducks/MamaDuck/platformio.ini
- library.json
- library.properties
- src/DuckUtils.cpp
- src/include/cdpcfg.h
Add crypto and CRC dependencies for PIO
Patch 2.1.16
> Update PIO dependencies

- src/DuckRadio.cpp
- src/include/DuckUtils.h
Signed-off-by: TimoWielink <timowielink@gmail.com>
Update Submodule Dependencies
patch
#239 
Still needs testing but need to open PR to test travis
> WIP Update submodules and fix Travis

- README.md
A clear and concise description of what you changed.
Patch, minor, or major.
> added townhall and roadmap links, removed Captive Portal section

- README.md
- examples/1.Ducks/PapaDuck/platformio.ini
Quick fix issue #264 
Patch
No version update needed
> Travis link fix

- README.md
- examples/1.Ducks/PapaDuck/PapaDuck.ino
- library.json
- library.properties
- src/CdpPacket.h
- src/DuckNet.cpp
- src/DuckUtils.cpp
- src/Ducks/MamaDuck.cpp
- src/Ducks/PapaDuck.cpp
- src/PapaDuck.h
- src/circularBuffer.cpp
- src/include/DuckNet.h
- src/include/cdpHome.h
- src/include/circularBuffer.h
- src/include/index.h
- src/include/messageBoard.h
Adds a message board that displays a set number of messages with the message board message topic received from a Papa Duck. The message board is accessible from the cdp home page. 
new feature
> Add Message Board Feature

- .gitignore
- src/include/cdpcfg.h
Fix the Display for the ttgo_lora32_v21 board
Minor
No
No
> Fix pins for the ttgo_lora32_v21 board

- examples/5.Custom-Papa-Examples/Papa-Downtime-Counter/Papa-Downtime-Counter.ino
there needs to be a distinction between health messages from Ducks and the health message from papa since they collect different data points
A clear and concise description of what you changed.
minor
> changed topic for papa downtime health message

- examples/5.Custom-Papa-Examples/PaPi-DMS-Lite-Examples/Serial-PaPiDuckExample/Serial-PaPiDuckExample.ino
Serial-PaPiDuckExample now handles/executes commands received via Serial from DMS-Lite.
Corresponds to [Pull-Request on DMS-Lite](https://github.com/Project-Owl/dms-lite-docker/pull/12)
minor
no
Uses the same gotMsg() function as the IBM-cloud version for easier maintenance.
Test by sending serialized JSON-Objects (e.g. {"topic":" /wifi/", "payload":"1"} to enable WiFi on all ducks)
> Executes Duck Commands received via Serial

- ClusterDuck-Protocol-Technical-Charter.pdf
- README.md
Add the required Technical Charter, signed with the LF on February 13, 2020. Slight formatting changes to Markdown and how the Town Hall link is shown.
Minor
No
We should probably review the part about the livestream
> Add Technical Charter and lint Markdown in README.

- .travis.yml
- README.md
- library.json
- library.properties
- src/DuckUtils.cpp
The Travis CI build has been failing for some time. This is due to a GitHub repository dependency in the script that no longer exists. The build script has been updated with some code that replaces `arduino-deps-installer` with some custom code.
NA
No
NA
> Updating Travis build to hopefully work

- library.json
- library.properties
Added the PubSubClient to the libraries.json and libraries.properties files.
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/304
> added pubsub client to libraries

- .github/pull_request_template.md
Added a prompt for developers to provide details on how others can test the developer's pull request. 
minor
> added testing methodology

- .github/pull_request_template.md
Updated the above choices as we also have PRs for infrastructure, build system updates
**Testing Methodology**  
The new PR template will be available once this PR is merged.
**Checklist**
_General_  
Tested Targets (Please check all that apply)
> Added Infrastructure as a choice for What is this PR for

- tools/license_updater.py
Creates a script for batch updating copyright and license SPDX headers in source file
#368 
**Testing Methodology**  
Did a dry run on all source files in CDP
Note: This is just the script to perform the code update.
We should decide when to actually update the CDP sources with the SPDX headers
**Checklist**
_General_  
Tested Targets (Please check all that apply)
> License And Copyright Updater

- .github/pull_request_template.md
Slight updates to the PR template
[Please provide the link.](https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/issues/368)
**Testing Methodology**  
It'll be seen after merge
Should be merged after the issue above is addressed
**Checklist**
_General_  
Tested Targets (Please check all that apply)
> Lint Markdown and add item for copyright/license

- library.json
Updates the library.json to we can correctly publish CDP to platformio registry
**Testing Methodology**  
Used the command `platformio publish pack` to generate a tarball and verified all required files are included
**Checklist**
_General_  
Tested Targets (Please check all that apply)
> Updated library.json to comply with platformio publishing

- docs/custom_dark.css
- docs/main.md
Update text and links about CDP in Doxygen main file
#406 
Test by looking at deployed GH pages
> Update Doxygen Intro text

- tools/CDP_CLI.md
- tools/cdp.py
Fixed  the CLI test command and added a readme for the tool usage
#403
Run unit test on a device using the CDP CLI tool
**Checklist**
_General_  
> 403 cdp cli test command failure

- .github/workflows/arduino_ci.yml
- examples/5.Custom-Board/DuckLink/my-boards/heltec-cubecell-gps/pio_cubecell_gps.ini
- library.json
- library.properties
- platformio.ini
- src/config/cdp_common_test.ini
-Update Actions to v3
-Update RadioLib to 6.6.0
-Change C++ Standard to 20
> Update Build Pipeline

- docs/assets/images/cdp_logo_transparent.png
- docs/assets/images/cdp_logo_transparent_small.png
- docs/assets/images/cdp_logo_white_bkg.png
- Documentation update
Update Logos in LFS Storage
> Change CDP Logo

- src/Ducks/PapaDuck.cpp
Enables Papa Ducks to be tested with a Detector Duck
Flash a papa duck and a detector duck, and see if the detector duck LED changes color to match the rssi in the serial logs
> add ping response for detector duck

- platformio.ini
- src/include/boards/README.md
Documentation update pursuant to #355
> Board contrib

- examples/Custom-Papa-Examples/AWS-PapaDuck/AWS-PapaDuck.ino
I forgot to add the `.c_str()`.
**Checklist**
> String to std
