ClusterDuck-Protocol/ClusterDuck-Protocol

doc/howToBuildADuck.md
just some added empty lines to fix rendering issues in the PDF version of HowToBuildADuck.
the to-PDF tooling seems to be more picky about markdown interpretation than the webviewer. 
Not-Just-Signed-Off-By-But-Actually-Signed: gozu42 <tvguho-tbmh42-tct.76b2756e@hashmail.org>
=> add newlines before block/style changes to pacify md-to-pdf tooling

ClusterDuck.cpp
briefly commenting on the individual commits.
let me know if you prefer to get stuff like this as individual pull requests.
i filed this as one PR for now to avoid additional merge commits.
first is mainly just a cleanup of the Serial.print debuglogging to make it easier to figure out where all the quacking on serial is coming from, and why.
as a next step (once i get tired by too much logging) i would like to add some minimal #define "logging framework" that toggles these debugprints based on a #defined loglevel.
the changed memset avoids hard crashes on receive errors, but really also needs the transmission buffer size replaced by a #define to avoid inconsistent assumptions about the buffer size.
i would also like to change most of the other memset to use the same define.
as in, the …
=> cleanup logging, some bugfixing

ClusterDuck.cpp, cdpcfg.h
I added a Username and Password protection for the /update URL so only the owner of the duck is able to reflash it.
Username and password are set to default in the CDPCFG.h file on the top:
`#define CDPCFG_UPDATE_USERNAME "username"
#define CDPCFG_UPDATE_PASSWORD "password"
`
=> Add Password protection for OTA updates

ClusterDuck.cpp, cdpcfg.h, library.json, library.properties
bulk PR of minor things that piled up here in the last days:
* bdd54d5 is the lora-dumper compatible debugprinting of lora pkts. 
* * the tohex helper function is needed because arduino String(blah,HEX) doesnt add a leading 0 so there would be need for a helper-function that checks each byte for being >15 and adding a 0 if not anyways.
* * i prefer a "clean" function over a "workaround for builtin" one in this case.
* * it uses the arduino String function for the result but avoids memory reallocation/fragmentation by pre-allocating the output string. (which is easy since we know exactly how many chars we are going to need from the start)
* 18267ca adds and documents two ways for overriding all or parts of cdpcfg
* 2f7f206 moves around config defines to separate all pin/hardware related …
=> Kw25 collection of minor features and fixups

doc/howToBuildADuck.md
The code block was missing a line break that broke Markdown. It fixes both the Markdown file itself as well as the generated PDF that comes from it.
Amended to correct DCO.
=> Fix Markdown that throws off PDF generation.

examples/PapaDuckExample/PapaDuckExample.ino
Just added space for the null char in the topic.
Changed line number 112 from 
int len = loc.length();
to
to int len = loc(length() + 1);
=> Possible fix for issue # 115 "papaduck example mqtt size off by one char"

src/ClusterDuck.cpp, src/ClusterDuck.h
When testing with a full cluster `LINK -> MAMA -> PAPA ---> (DMS)` The Link messages where not being relayed by the mama duck. Instead an empty message was sent.
The issue was the `_lastPacket` global variable was still defined in _ClusterDuck.cpp_ and was used when sending the payload, instead of the `_lastePacket` now defined in the DuckLora component.
This did cause some other side effects in DMS (e.g empty/rogue message, incorrect paths, etc..)
I tested with a full cluster and it working now. Also tested the Portal message, it is now correctly received and shown in DMS.
=> Fixes mana duck message relay issue

.gitmodules
@amirna2 build this new code for the CDP and we found a small compatibility issue with the SX127x Lora Module. Project OWL forked RadioLib and @amirna2 made a small patch to fix the compatibility issues. We will use the forked Library as the new Submodule for the CDP until the patch is fixed in the RadioLib upstream.
=> Add Forked RadioLib to Submodules 

src/Ducks/PapaDuck.cpp
Had issue when using dynamic SSID and Password credentials it would prevent the webserver from being created. Conditional was moved to only encapsulate the setupInternet. This allows the webserver to still be created so that the SSID and Password can be entered in later.
=> fix setupInternet conditional

examples/6.PaPi-DMS-Lite-Examples/PapiDuckExample-wifi/PapiDuckExample-wifi.ino, examples/6.PaPi-DMS-Lite-Examples/Serial-PaPiDuckExample/Serial-PaPiDuckExample.ino
---
name: Feature change
about: Provide code that changes functionality
title: 'add topic-string to json-fields'
labels: 
assignees: 
---
Adds the TopicString to the json which is transmitted to the dms-lite
Patch
It supplements changes made to the dms-lite repository.
See: https://github.com/Project-Owl/dms-lite/pull/23
To keep it simple, the same TopicStrings as for the Cloud-DMS are used.
=> Add TopicString to Json fields

.travis.yml, examples/1.Ducks/PapaDuck/PapaDuck.ino, examples/7.TTGO-TBeam-Examples/TTGO-Telemetry/TTGO-Telemetry.ino, examples/9.Telemetry/Papa-Downtime-Counter.ino/Papa-Downtime-Counter.ino
---
name: PapaDuck Disconnect Telemetry
title: 'Papa and Mama Telemetry Examples'
labels: 'Telemetry'
assignees: 'Nick Feuer'
---
Added telemetry examples for Papa and TTGO. This will help better understand device performance in the field.
Minor
Added new telemetry collection files for PapaDuck and TTGO MamaDucks. The PapaDuck-Disconnect-Counter will send connection reports that can be used against packet loss data. TTGO MamaDuck will send reports on battery power, charging status, board temperature, and gps location. This currently only works on TTGO devices.
=> PapaDuck Disconnect Telemetry

README.md, examples/1.Ducks/PapaDuck/PapaDuck.ino, library.json, src/DuckUtils.cpp
Followup from #200
When I try running the version of PapaDuck.ino before this commit, it's not able to connect:
```
11:29:17.650 -> [INF: Duck.cpp]  setupSerial rc = 0
11:29:17.650 -> [INF: Duck.cpp]  setupDeviceId rc = 0
11:29:17.687 -> [INF: Duck.cpp]  setupRadio rc = 0
11:29:17.797 -> [D][WiFiGeneric.cpp:374] _eventCallback(): Event: 0 - WIFI_READY
11:29:17.797 -> [D][WiFiGeneric.cpp:374] _eventCallback(): Event: 14 - AP_START
11:29:17.983 -> [INF: DuckNet.cpp]  Created Wifi Access Point
11:29:18.021 -> [INF: Duck.cpp]  setupWifi OK
11:29:18.021 -> [INF: DuckNet.cpp]  Created local DNS
11:29:18.021 -> [INF: Duck.cpp]  setupDns OK
11:29:18.021 -> [INF: DuckNet.cpp]  Setting up Web Server
11:29:18.021 -> [DBG: DuckNet.cpp]  Web Server using main page
11:29:18.021 -> [INF: Duck.cpp] …
```
=> fix CA_CERT ifdef else condition

src/DuckDisplay.cpp, src/DuckDisplay.h
- Primary improvement: removed include to iostream when no display is available
- Removed member variables from DuckDisplay when no display is available
- Moved ClusterDuck includes to .cpp file
- Improved readability of some `#endif`s
For boards without a display:
- ~169 KB storage saved, reduced by ~13%
- ~5.4 KB dynamic memory saved, reduced by ~10%
Patch
No (but there was helpful, [related conversation](https://clusterduck-protocol.slack.com/archives/CLJ3L5KC4/p1623111379103600) in the Slack about a week ago)
I was running into memory issues (board was continuously resetting / stack overwriting …
=> src: reduce storage space by ~169 KB when no display

src/DuckDisplay.cpp
Saves ~169KB of storage space. Similar to PR #215
Patch
No
DuckDisplay.cpp is still being compiled because ["source code found in src folder and all its subfolders is compiled and linked in the user’s sketch"](https://arduino.github.io/arduino-cli/latest/library-specification/), but now it's ~169KB smaller (in terms of storage space).
=> removed iostream include from oled devices

src/DuckUtils.cpp
Signed-off-by: Amir Nathoo <amir.nth@gmail.com>
Updated DuckUtils to use `random(max)` as this is supported by all platforms
Patch
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/220
Tested on the following boards: Heltec WiFi v2, Arduino Zero USB and Heltec CubeCell AB01
=> Use random(max) as this is supported by all platforms

src/ClusterDuck.h, src/DuckUtils.cpp, src/include/DuckUtils.h
Fixes warning when using verbose compilation. volatile is ignored when it's declared as part of the return type of a function, and that makes sense because it's returning a copy of the volatile variable.
Patch
No
Verbose compilation should be used more often. It catches real issues, like the missing returns that @amirna2 recently fixed in #217.
=> fix volatile qualifier

src/DuckEsp.cpp, src/Ducks/Duck.cpp, src/Ducks/DuckDetect.cpp, src/Ducks/DuckLink.cpp, src/Ducks/MamaDuck.cpp, src/Ducks/PapaDuck.cpp, src/include/Duck.h, src/include/DuckEsp.h
Logs warnings to the device's serial output when the heap memory
is too low to allocate a new Cdp packet.
Fixes: https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/237
=> src: output warning if heap runs low on memory

README.md, library.json, library.properties, src/DuckNet.cpp, src/DuckUtils.cpp, src/include/DuckNet.h, src/include/DuckUtils.h
* Move the functionality of saving the WiFi credentials to EEPROM to
the saveWifiCredentials function in DuckUtils
* Move the functionality of loading the WiFi credentials from EEPROM to
the loadWifiSsid and loadWifiPassword functions in DuckUtils
Patch
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/231
=> src: move EEPROM methods from DuckNet to DuckUtils

README.md
There is a grammatical error in the read me. It is missing the preposition "of" in line 16  between "advantage "and "a".
_" as it takes advantage _ a system..."_
Extremely minor change to the readme.
No.
Grammatical correction.
=> missing preposition in line 16 of Readme

src/include/cdpcfg.h
This addresses two fixes for the TTGO T-Beam,
1. The compiler flag was incorrect, which caused build issues and the board defaulted to a Heltec board.
2. The OLED SDA/SCL pins were backwards, which caused the OLED to not properly initialize.
Patch
No
Issues which lead to my patch were observed using a LILYGO TTGO T-Beam in PlatformIO
=> Fix board configuration typos in TTGO T-Beam

README.md, library.json, library.properties, src/CdpPacket.h, src/DuckNet.cpp, src/DuckUtils.cpp, src/Ducks/Duck.cpp, src/Ducks/MamaDuck.cpp, src/Ducks/PapaDuck.cpp, src/circularBuffer.cpp, src/include/Duck.h, src/include/DuckNet.h, src/include/cdpHome.h, src/include/chatPage.h, src/include/privateChat.h, src/include/privateChatPrompt.h
src: Added a private and global chat feature between ducks, available through the cdp home page. Currently, up to 3 private chat histories are held on a duck.
new feature
**To Do**
- make chat bar more responsive
- fix validation for dduid on chat prompt page
- display the dduid on the private chat header bar
- submit chat message when pushing enter (vs only the send button)
- add automatic scrolling to bottom of chat
- fix chat bar overlapping the latest message
- fix message age display: time is wrong on only your own (not the other device's) messages after page refresh
=> Public and Private Chat Feature Between Ducks

examples/1.Ducks/MamaDuck/platformio.ini, examples/1.Ducks/PapaDuck/platformio.ini
This commit is able to successfully build MamaDuck and PapaDuck.
Patch.
There are known issues that have easy fixes:
- While Compiling MamaDuck, an error may appear in AES.h. the fix is to
comment out #if part and only keep the define under #else.
- Other examples than PapaDuck and MamaDuck may have different lib_deps.
But this should be a matter of just adding libraries to pio.ini files
of respective examples.
Signed-off-by: Dhruva Gole <goledhruva@gmail.com>
=> Fix PIO build errors

src/DuckNet.cpp, src/include/DuckNet.h, src/include/cdpHome.h, src/include/chatPage.h, src/include/chatPrompt.h, src/include/privateChat.h, src/include/privateChatPrompt.h
Replaces the message age in global and private chat with a username stored in the client's `sessionStorage`, which is cleared on closing of the tab/window. Adds a prompt before global chat for entering a username.
Known issues: 
- Opening an existing private chat history when the username has 
not been set in this tab sets the username to null
- Chat prompt inputs are not being enforced as `required`
patch
=> src: replace message age in chats with username

examples/1.Ducks/PapaDuck/PapaDuck.ino, examples/5.Custom-Papa-Examples/Papa-DishDuck-WiFi/Papa-DishDuck-WiFi.ino, examples/5.Custom-Papa-Examples/Papa-Downtime-Counter/Papa-Downtime-Counter.ino, examples/7.Encryption/DecryptionPapaDuck/DecryptionPapaDuck.ino, src/DuckNet.cpp, src/include/cdpcfg.h
Fixes bug where global chat disappears before visiting private chat, filters out pchat topic from being sent to DMS, and adds a config variable for chat buffer sizes.
Patch
**Steps to test**
- Global Chat
1. Deployed two ducks, 1 MamaDuck and 1 PapaDuck
2. Connect to the MamaDuck
3. Enter the captive portal
4. Go to “Global Chat”
5. Submit any message
6. see that message pop up on the global chat
7. Connect to the PapaDuck
8. Enter the captive portal
9. Go to “Global Chat”
10. Confirm that the message sent from the MamaDuck is there
- Private Chat
1. Connect to the MamaDuck
2. Enter the captive portal
3. Go to “Private Chat”
4. Add the PapaDuck (the deviceID of PapaDuck, default is PAPAUCK) as the destination device
5. …
=> Chat disappearance fix, filter out pchat from DMS

src/include/index.h
There should be a character limit in the captive portal message to prevent anyone from breaking a CDP packet. Using Amir's code, it limits the message to 200 characters and shows how many characters left.
patch
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/307
**Testing Methodology. How can someone test your pull request?** 
Upload the firmware into a device and open the captive portal. Select "Send a Message" and type in a message. The limit should be 200 characters and there should be a prompt showing the number of remaining characters left. The message should send as normal. 
Add any …
=> added amirs text limitation

examples/6.TTGO-TBeam-Examples/TBeam-Telemetry/TBeam-Telemetry.ino
I added a free heap memory into the telemetry data for the T-Beam.
patch
https://github.com/Call-for-Code/ClusterDuck-Protocol/issues/196
To test this pull request, you will need a TBeam. Upload the example in Ducks-> TTGO-TBeam-Examples-> TBeam-Telemetry-Example and the free memory will be sent.
=> added free memory data

README.md, examples/1.Ducks/PapaDuck/PapaDuck.ino, examples/1.Ducks/PapaDuck/secrets.h, library.json, library.properties, src/DuckUtils.cpp
I have converted the PapaDuck Example to work with AWS IoT core instead of the discontinued IBM Watson IoT Platform
Minor
**Testing Methodology. How can someone test your pull request?** 
Follow the instructions created [here](https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/Setting-up-AWS-IoT-Core-endpoint)
Wiki has also been updated [here](https://github.com/Call-for-Code/ClusterDuck-Protocol/wiki/Setting-up-AWS-IoT-Core-endpoint)
=> update Papa example

examples/1.Ducks/MamaDuck/MamaDuck.ino, examples/6.TTGO-TBeam-Examples/TBeam-Telemetry/TBeam-Telemetry.ino
In order for `freeMemory()` to work the `MemoryFree.h` needed to be included. I added that header into the ino files.
patch
**Testing Methodology. How can someone test your pull request?** 
Test the `examples -> 1. Ducks -> MamaDuck -> MamaDuck.ino` and `examples -> 6.TTGO-TBeam-Examples -> TBeam-Telemetry` to see if it compiles and the Free memory is printing in the serial monitor
=> added freememory header

platformio.ini
Fixes broken build issue issue with CubeCell Board v2
#412
Run the build command `platformio run -e cubecell_board_v2 `
The build failure was caused by and incorrect `extends` statement
```
[env:cubecell_board_v2]
extends = ${env.cubecell_base}
```
The correct statement is `extends = cubecell_base`
**Checklist**
_General_  
=> Fixed issues in platformio for cubecell v2. Switch compiler to gnu++11

examples/Basic-Ducks/DetectorDuck/platformio.ini, examples/Basic-Ducks/DuckLink/platformio.ini, examples/Basic-Ducks/MamaDuck/platformio.ini, examples/Basic-Ducks/PapaDuck/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Detect/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Example/platformio.ini, examples/Custom-Papa-Examples/AWS-PapaDuck/platformio.ini, examples/Custom-Papa-Examples/MQTT-PapaDuck/platformio.ini, examples/External-Boards-Example/DuckLink/my-boards/heltec-cubecell-gps/pio_cubecell_gps.ini, examples/External-Boards-Example/DuckLink/my-boards/heltec-wireless-paper/pio_wireless_paper.ini
Switch to using the release tags instead of master for CDP's pio dependency
=> Use Latest Release Tag for PIO CDP Install

examples/Basic-Ducks/DetectorDuck/platformio.ini, examples/Basic-Ducks/DuckLink/platformio.ini, examples/Basic-Ducks/MamaDuck/platformio.ini, examples/Basic-Ducks/PapaDuck/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Detect/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Example/platformio.ini, examples/Custom-Papa-Examples/AWS-PapaDuck/platformio.ini, examples/Custom-Papa-Examples/MQTT-PapaDuck/platformio.ini
Updated outdated default_envs `local_ttgo_t_beam` to `local_ttgo_lora32_v1` and `prod_ttgo_t_beam` to `prod_ttgo_lora32_v1` across all example `platformio.ini`
https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/issues/454
PR was built without any errors
**Checklist**
_General_  
=> Issue-454: Updated outdated example default_envs vars

examples/Basic-Ducks/DetectorDuck/DetectorDuck.ino
A bottom threshold for the detector duck was added for low signal. We want to have a little cushion for the low signal to add the next node. 
No
Upload two MamaDucks and a DetectorDuck. Deploy a MamaDuck and then turn on a DetectorDuck. Walk away from the MamaDuck with the DetectorDuck and check to see if the light turns from Green -> Blue -> Purple -> Red. 
**Checklist**
_General_  
=> added threshold for "low signal"

examples/Basic-Ducks/DetectorDuck/DetectorDuck.ino, examples/Basic-Ducks/DetectorDuck/platformio.ini, src/Ducks/DuckDetect.cpp, src/Ducks/MamaDuck.cpp, src/Ducks/PapaDuck.cpp
Ducks respond to DetectorDuck's pings using a Pong. The pong should be ignored by all the Ducks except for the DetectorDuck. At the moment, the MamaDucks relay pongs and the PapaDuck uploads the pong to the cloud. This PR makes sure that the PapaDuck and MamaDuck ignores those pongs. Also a timer for signal lost was added to the Detector Duck to turn red if there are no pongs.
No.
Upload a standard mesh network (PapaDuck, MamaDuck) and a DetectorDuck. The DetectorDuck should turn colors based on the RSSI values, while the MamaDuck and PapaDuck should be sending PINGs but ignoring PONGs. …
=> Ignore pongs

examples/Basic-Ducks/DuckLink/platformio.ini, examples/Basic-Ducks/MamaDuck/platformio.ini, examples/Basic-Ducks/PapaDuck/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Detect/platformio.ini, examples/Custom-Mama-Examples/Custom-Mama-Example/Custom-Mama-Example.ino, examples/Custom-Mama-Examples/Custom-Mama-Example/platformio.ini, examples/Custom-Papa-Examples/AWS-PapaDuck/AWS-PapaDuck.ino, examples/Custom-Papa-Examples/AWS-PapaDuck/platformio.ini, examples/Custom-Papa-Examples/MQTT-PapaDuck/MQTT-PapaDuck.ino, examples/Custom-Papa-Examples/MQTT-PapaDuck/platformio.ini, examples/External-Boards-Example/DuckLink/DuckLink.ino, examples/External-Boards-Example/DuckLink/my-boards/heltec-cubecell-gps/pio_cubecell_gps.ini, examples/External-Boards-Example/DuckLink/my-boards/heltec-wireless-paper/pio_wireless_paper.ini, library.json, library.properties, platformio.ini, src/DuckDisplay.cpp, src/DuckDisplay.h, src/include/cdpcfg.h
Final testing and bug fixes for CDP v4.3.0 release. Changes made in this release:
* GPS support  through TinyGPS++
* Updates for RadioLib v7
* Fixes for various example sketches
* Remove Cubecell Support
* Replacing Arduino String with std::string and byte vectors with STL containers
* Fixes to the Captive Portal
_Full Network Test_
For the full network test, set up 
1. an AWS Papa or mqtt Papa
2. Two Mama Ducks, one using cdp v4.2.0 and one using local
3. one duck link
4. Test a detector duck with each of the 4 other ducks above
Make sure to use different device types if you can!
=> Release 4.3.0

examples/Custom-Papa-Examples/AWS-PapaDuck/AWS-PapaDuck.ino
There were a couple of `String` in AWS Papa. I converted it to `std::to_string`
**Checklist**
=> changed to std::to_string

src/Ducks/Duck.cpp, src/include/Duck.h
There are two instances that we set the name of the Duck: `duid` and `duckName`. At the moment, `duckName` is set to "" and the getter function to retrieve the name of the duck returns`duckName`. Therefore, I removed (commented out) duckName and made a getter function to retrieve `duid`. 
**Checklist**
=> Get Duck Name

examples/Custom-Papa-Examples/AWS-PapaDuck/AWS-PapaDuck.ino
The `gotMsg` function was called before it was declared. Therefore I moved the call after it was declared.
**Checklist**
=> changed location of PubSub

library.json
The PIO crawler wont work since we cant define specifric ESP32 versions in the library.json file
=> Fix PIO registry crawler

src/DuckNet.cpp, src/DuckPacket.cpp, src/DuckRadio.cpp, src/Ducks/MamaDuck.cpp, src/Ducks/PapaDuck.cpp, src/include/DuckPacket.h
A brief description of changes made in this PR.
This is just cleaning up some usages of Arduino's `byte` typedef keyword I intended to go in as part of #496.
#496
**Checklist**
=> Changes away from byte

src/CdpPacket.h, src/DuckNet.cpp, src/DuckPacket.cpp, src/DuckRadio.cpp, src/Ducks/Duck.cpp, src/Ducks/MamaDuck.cpp, src/Ducks/PapaDuck.cpp, src/include/Duck.h, src/include/DuckPacket.h, src/include/DuckUtils.h
A brief description of changes made in this PR.
I made `UpdateRREQ()` and `RREQ()` static and public because they have to be used in `MamaDuck.cpp`, which is outside the `DuckPacket` class.
none
**Checklist**
=> changes to DuckPacket
